apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: ClusterIP
  selector:
    app: django-web
  ports:
  - port: {{ .Values.django.port }}
    targetPort: {{ .Values.django.port }}
