apiVersion: v1
entries:
  django-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-08-20T09:11:34.699498909+03:00"
    description: A Helm chart for Kubernetes
    digest: 6fd1acc775c37ed94b4466495721553efa8439abcc00e3e26832bf0da77fa842
    name: django-chart
    type: application
    urls:
    - https://omerkisa1.github.io/rke2-gitops-platform/charts/django-chart-0.1.0.tgz
    version: 0.1.0
generated: "2026-08-20T09:11:34.699151043+03:00"
