apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: {{ .Values.jenkins.namespace }}
spec:
  ingressClassName: {{ .Values.jenkins.ingressClass }}
  rules:
    - host: {{ .Values.jenkins.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.jenkins.serviceName }}
                port:
                  number: {{ .Values.jenkins.servicePort }}
